/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_JniUtils */

#ifndef _Included_com_test_JniUtils
#define _Included_com_test_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_JniUtils
 * Method:    sendPoint
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_test_JniUtils_sendPoint
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
